services:
  mysql:
    build:
      context: ./middleware/mysql
      dockerfile: Dockerfile
    container_name: contact-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: contact_db
      MYSQL_USER: contact_user
      MYSQL_PASSWORD: contact_pass
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
    networks:
      - contact_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
  mysql_logs:
    driver: local

networks:
  contact_network:
    driver: bridge
